# Generated by Django 6.1.1 on 2026-09-07 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección de Envío')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad / Comuna')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=True, verbose_name='Pagado')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Tarjeta de Crédito / Débito'), ('webpay', 'Webpay Plus / Transbank'), ('bank_transfer', 'Transferencia Bancaria Directa')], default='credit_card', max_length=20, verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='orders_orde_created_743fca_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(default='40', max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.product')),
            ],
        ),
    ]
